apiVersion: v1
kind: Pod
metadata:
  name: nginx-w-label
  labels:
    team: finance
    version: 1.0.0
    environtment: production
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80