apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web
  labels:
    name: nodejs-web
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nodejs-web
  template:
    metadata:
      name: nodejs-web
      labels:
        name: nodejs-web
    spec:
      containers:
        - name: nodejs-web
          image: kalislami/nodejs-web:1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m #mili core
              memory: 500Mi #mebibyte
            limits: # set >= request
              cpu: 200m #mili core
              memory: 1000Mi #mebibyte

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-web-service
spec:
  type: NodePort
  selector:
    name: nodejs-web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001