apiVersion: v1
kind: Pod
metadata:
  name: nginx-gpu
spec:
  nodeSelector:
    gpu: "true" #ambil dari label node
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80